### ISSUE TITLE
System Window Decoration

### ISSUE THREAD

**Issue by tio-trom** [prateekmedia/appimagepool#74] opened 2022-07-21 02:01 UTC
Is it possible to please add and enable a system window decoration? Without it we lose functionality (the right click that allows users to move windows on different workspaces and so much more) + usability (does not respect the system's theme). Thanks!

**Comment by prateekmedia** [comment] 2022-08-07 05:51
Added the first one, will not add the second one as we strictly follow libadwatia's guidelines as of now, You can check the nightly version in README to test this.

**Comment by prateekmedia** [comment] 2022-08-07 06:18
This issue is a duplicate of #11 and #47

**Closed by prateekmedia** 2022-08-07 06:18 UTC

**Comment by tio-trom** [comment] 2022-08-07 12:31
Thank you!
